brews:
  - name: jumper
    tap:
      owner: M-Porter
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: Matt Porter
      email: mtp5129@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/M-Porter/jumper"
    license: "MIT"
    description: "Quickly jump to your project directories"
    caveats: |
      Run `jumper setup` for setup instructions.
    install: |
      bin.install "jumper"
